version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Prowler and dependencies..."
      - pip3 install prowler
      - prowler -v
      - mkdir -p output

  build:
    commands:
      - |
        export OUTPUT_FORMATS="csv json-ocsf html"
        export TIMESTAMP=$(date +%B-%Y)
        mkdir -p output/$TIMESTAMP

        echo "Using account list override: $MULTI_ACCOUNT_LIST_OVERRIDE"
        account_list=$MULTI_ACCOUNT_LIST_OVERRIDE

        PARALLEL_ACCOUNTS=8  # You can tune this based on compute specs (see guidance below)

        for accountId in $account_list; do
            test "$(jobs | wc -l)" -ge $PARALLEL_ACCOUNTS && wait || true
            {
                echo "Scanning account $accountId"
                prowler aws --output $OUTPUT_FORMATS --output-file-format single \
                  --role arn:$AWS_PARTITION:iam::$accountId:role/$PROWLER_ROLE \
                  --output-path output/$TIMESTAMP/$accountId
            } &
        done

        wait

  post_build:
    commands:
      - echo "Zipping all outputs..."
      - cd output && zip -r $TIMESTAMP.zip $TIMESTAMP && cd -

      - echo "Uploading to S3..."
      - aws s3 cp output/$TIMESTAMP.zip s3://$BUCKET_REPORT/$TIMESTAMP/

      - echo "Done!"
